#!/bin/bash
#curl -H "Content-Type: application/json" \
#     -d '{ "name": "White House Honey Ale"
#         , "beerStyle": {"id": "8"}
#         , "regionalStyle": {"id": "4"}
#         , "beerColor": {"id": "2"}
#         , "description": "Ale to the Chief! This original recipe, first customized and brewed by the White House kitchen staff, is now available by popular demand as a Northern Brewer kit. Built on a big foundation of malt with strong tones of biscuit and toffee, the Honey Ale plays up the fruity, caramel aspects of English malt and yeast. But much like the Founding Fathers would have spiced up traditional style ales with homegrown ingredients, a late addition of pure honey adds a revolutionary twist. Declare your independence from mediocre beers with this historic White House Homebrew!"
#         }' \
#         localhost:8080/my-brews/api/beers

curl -H "Content-Type: application/json" \
     -d '{ "name": "Caribou Slobber"
         , "beerStyle": {"id": 5}
         , "regionalStyle": {"id": 4}
         , "beerColor": {"id": 3}
         , "description": "Your new favorite session beer. Dense layers of malt, caramel, baking chocolate, and a hint of light-roast coffee give way to reveal a hop character you\u0027ll be surprised to find if you\u0027re used to drinking English brown ale."
         }' \
         -i localhost:8080/my-brews/api/beers

curl -H "Content-type: application/json" \
     -d '{ "name": "Bourbon Barrel Porter"
         , "beerStyle": { "id": 14 }
         , "regionalStyle": { "id": 4 }
         , "beerColor": {"id": 3}
         , "description": "Bourbon barrel-aged beers have been a hugely popular style ever since their inception in the early \u002790s by American craft brewers. By starting with a stronger-than-average robust porter, then infusing it with Bourbon-soaked oak (we recommend Maker\u0027s Mark), the end result is quite possibly the best beer ever."
         }' \
         -i localhost:8080/my-brews/api/beers
         
curl -H "Content-type: application/json" \
     -d '{ "name": "Honey Brown Ale"
         , "beerStyle": { "id": 5 }
         , "regionalStyle": { "id": 4 }
         , "beerColor": {"id": 2}
         , "description": "What would happen if you augmented the slightly dry, caramelly and roasty character of a smooth, mellow English brown ale with the sweet floral flavor of honey? What if you added the honey at the very last possible minute to maximize its presence in the finished beer? What if it was delicious? This recipe is a spinoff of our highly popular Nut Brown Ale kit that combines American malts, hops and ale yeast with honey. A well-balanced and intensely drinkable beer."
         }' \
         -i localhost:8080/my-brews/api/beers
         
 curl -H "Content-type: application/json" \
     -d '{ "name": "Tru Hefe"
         , "beerStyle": { "id": 7 }
         , "regionalStyle": { "id": 3 }
         , "beerColor": {"id": 1}
         , "description": "One of the signature brews of Bavaria, Hefeweizen is a medium-bodied, effervescent ale practically exploding with yeast and wheat malt character – kind of like a liquid multigrain bread. Our kit is 100% traditional—cloudy, malty, and spicy, with a smooth mouthfeel and dense, whipped-cream head. Serve in a tall glass \u0022mit hefe\u0022 - swirl the bottle to make sure you get all the yeast!"
         }' \
         -i localhost:8080/my-brews/api/beers
