#!/bin/bash
curl -H "Content-Type: application/json" \
     -d '{"name": "English Medium Crystal Malt"}' \
          localhost:8080/my-brews/api/grain

curl -H "Content-Type: application/json" \
     -d '{"name": "Belgian Biscuit Malt"}' \
          localhost:8080/my-brews/api/grain

